### ISSUE TITLE
Graph shows activity but 0 for stats

### ISSUE THREAD

**Issue by zippyy** [totoroot/hugo-github-calendar#1]
graph shows the activity but all 3 stat numbers are 0

**Comment by totoroot** [comment]
Hey @zippyy,

Thanks for reporting this! The global stats not being correctly displayed was due to an API change on GitHub's part which caused the underlying JS library to fail parsing the contribution stats. This was documented in issue https://github.com/Bloggify/github-calendar/issues/157#issuecomment-1375625663 of the github-calendar project.

I fixed the issue myself by contributing [this fix](https://github.com/IonicaBizau/github-calendar-parser/pull/25) to the parser, which got merged back in January.

Unfortunately I forgot to update this repo to use [the new version](https://github.com/Bloggify/github-calendar/releases/tag/2.3.2) initially.

The shortcode module has now been updated to use the latest version and should display everything correctly again.

Please let me know if I can close this issue.

**Comment by zippyy** [comment]
Awesome thanks, I just updated the submodule and its working now.
